repos:
  - repo: local
    hooks:
      - id: poly-prepare
        name: Run Poly Prepare
        entry: bash -c 'source .venv/bin/activate && python3 -m polyapi prepare'
        language: system
        types: [python]
        always_run: true
        additional_dependencies: []
