repos:
  - repo: local
    hooks:
      - id: poly-prepare
        name: Run Poly Prepare
        entry: python3 -m polyapi prepare
        language: system
        types: [python]
        pass_filenames: false
        additional_dependencies: []
